Add protection against calling unauthorized enpoints on guest devices.
vilppuvuorinen/pymelcloud pull request #10
Opened 2021-05-11 19:52 UTC by espenfjo

Calling `ListDeviceUnits` on devices which you are not the owner, but are granted control will return a 403 Forbidden error.
Adding this protection should not affect normal operation in Home Assistant or similar users of this library.
For Home Assistant the only side-effect is missing model number in the unit description.

2021-05-12 05:31 UTC, vilppuvuorinen commented
Looks good. I want to give it a go before merging which slows things down a touch.

Do you want to do the eventual home-assistant PR as well? This change will break the `device_info` property in the integration.

2021-05-12 06:04 UTC, espenfjo commented
This code is "only" used for setting the model number in `device_info`:
```python
unit_infos = self.device.units
if unit_infos is not None:
    _device_info["model"] = ", ".join(
        [x["model"] for x in unit_infos if x["model"]]
    )
```
Since `self.device.units` is `None` here the code will not try to create the model attribute, and since its not already defined in the code above it will not show up as `None`, `undefined` or any other "ugly" variant.

So a PR to Homeassistant shouldn't really be necessary?

2021-05-14 17:10 UTC, vilppuvuorinen requested changes
The CHANGLELOG should be updated. Something like

```
### Fixed
- Prevent forbidden request to `ListDeviceUnits` on guest devices.
```

You should also reword the commit message if possible, The actual message content is better than most of the commits in this repo so far, but I'd love to see the formatting follow the guidelines from this wonderful blog post: https://chris.beams.io/posts/git-commit/

2021-05-14 17:10 UTC, vilppuvuorinen commented on pymelcloud/device.py
> +        if self._device_units is None and self.device_owner_id == self.user_id:
My heat pump has `OwnerID` of `null`. I can't remember whether I've cleared the fields from the sample data, but none of the sample devices also have `null` `OwnerID`s.

2021-05-14 20:42 UTC, espenfjo commented
I did something else instead. Rather than comparing the current user with the device owner i check the access level.

Also added some tests.

2021-05-19 18:10 UTC, vilppuvuorinen approved these changes

2021-05-19 18:10 UTC, merged

2021-05-19 18:20 UTC, vilppuvuorinen commented
Thank you for the patch. I'll create a new release and then a PR to home assistant.

Please feel free to harass me here if either of these steps starts to drag on.